### ISSUE TITLE
Schedule Links not working although path seems correct

### ISSUE THREAD

**Issue by sapnanayak** [grvashu/srishti-live-17#122]
I dont know why this is happening.. the path seems to be right and even dreamviewer acknowledges the existence of the html pages. On my local the pages open but no header footer is seen.

**Comment by grvashu** [comment]
Ok. Checking.

**Comment by grvashu** [comment]
Are header and footer not appearing on all pages in the local preview?
This could be due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

This is a workaround for that in chrome: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en.
