### ISSUE TITLE
menu button not working on mobiles

### ISSUE THREAD

**Issue by NitishChopra09** [grvashu/srishti-live-17#126]
the button is not working on cellphones

**Comment by NitishChopra09** [comment]
we're trying to look into it. but can you too please check? even on the face of it - it looks like a bug that'd be hard to find.

**Comment by grvashu** [comment]
Found the cause: It is due to the fact that nav bar is located in the separate header.html file. For some reasons, this part file is not using the index file's js references.

Resolution: Copy the header section back in all the files and remove `<div w3-include-html="header.html"></div>`.

Note: No changes in footer required.
